system monitor: add diagnostic messages
bit-bots/bitbots_misc pull request #79
Opened 2020-11-18 16:09 UTC by SammyRamone

## Proposed changes
Adds publishing of diagnostic messages to the system monitor so that they are displayed in rqt diagnostic view.

## Related issues
partly solves https://github.com/bit-bots/bitbots_misc/issues/16

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2020-11-18 16:10 UTC, SammyRamone commented
works on my machine. maybe we want other metrics to launch warnings for network problems

2020-11-18 16:14 UTC, SammyRamone commented
needs https://github.com/bit-bots/bitbots_lowlevel/pull/68 to be launched corretly

2020-11-19 08:32 UTC, SammyRamone commented
opened an issue for starting this also on the odroid
https://github.com/bit-bots/bitbots_misc/issues/81

2020-11-19 08:33 UTC, SammyRamone commented
I tested it on the robot and it works. Can be merged, if you don't propose any changes for throwing warnings with the network interfaces

2020-11-19 10:33 UTC, timonegk requested changes

2020-11-19 10:33 UTC, timonegk commented on system_monitor/src/system_monitor/monitor.py
> +                -1, [])
```suggestion
                -1, [], 0)
```
Or some other default for `overall_usage_percentage`

2020-11-19 12:53 UTC, timonegk approved these changes

2020-11-19 16:17 UTC, merged